steps:

- id: 'Instalando NPM'
  name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- id: 'Iniciando test'
  name: 'gcr.io/cloud-builders/npm'
  args: ['test']

- id: 'Deploy app'
  name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]timeout: "1600s"
